name: Docker

on:
  push:
    # Publish `$default-branch` as Docker `latest` image.
    branches:
      - $default-branch

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  Test:
      runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test the build
        run: docker build .

  GitHub:
    name: GitHub Package Registry
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

       - name: Push to GitHub Container Eegistry
         run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/samproxy-fargate-image
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          # Use Docker `latest` tag convention
          [ "$VERSION" == "$default-branch" ] && VERSION=latest
          
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          
          docker tag samproxy-fargate-image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
